version: '3'

services: 
  portainer:
    image: portainer/portainer-ce
    container_name: portainer-service
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      net:
    ports:
      - 9500:9000

volumes: 
  data:

networks:
  net: